### ISSUE TITLE
提示 Invalid license key

### ISSUE THREAD

**Issue by scpmygit** [pengzhile/atlassian-agent#14]
jira 6.0.1

执行的命令

![Snipaste-20190329-154204](https://user-images.githubusercontent.com/19463834/55217162-c730fa00-5239-11e9-824b-29a2fd721431.png)

catalina.out  里也没有错误信息

**Comment by scpmygit** [comment]
补充一下。
从数据库里删除已有的 license
使用 atlassian-agent-v1.2.2/atlassian-agent.jar 得到 license code
贴到 Jira 里，报错 

![image](https://user-images.githubusercontent.com/19463834/55217531-b59c2200-523a-11e9-9ecf-a971fe6c4351.png)

**Comment by pengzhile** [comment]
先配置好agent，在catalina.out里看到=== agent working ===

**Comment by scpmygit** [comment]
日志里面是有 agent working 的

![image](https://user-images.githubusercontent.com/19463834/55219294-876d1100-523f-11e9-8d48-ac045009a793.png)

进程里面也是可以看到 

 -javaagent:/opt/atlassian/atlassian-agent-v1.2.2/atlassian-agent.jar


在 catalina.2019-03-29.log 看到

Mar 29, 2019 3:14:06 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/opt/atlassian/atlassian-agent-v1.2.2/atlassian-agent.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
        at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:131)
        at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:209)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:119)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2066)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1942)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1908)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1893)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1296)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:346)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5173)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by pengzhile** [comment]
你用的是我release的atlassian-agent.jar吗？

**Comment by scpmygit** [comment]
> 你用的是我release的atlassian-agent.jar吗？

是的，从 release 里下载的 1.2.2

**Comment by pengzhile** [comment]
你之前用其他工具破解过吗？破解过的文件是否恢复了？

**Comment by scpmygit** [comment]
破解过，但不是我操作的，不知有哪些文件受影响，更不知从哪里恢复

今天是通过在操作数据库来移除 license 的

`delete from propertytext where id = '10015';`

**Comment by pengzhile** [comment]
你先装个测试环境折腾看看吧。
