### ISSUE TITLE
8.1 无法激活

### ISSUE THREAD

**Issue by zfavourite99** [pengzhile/atlassian-agent#19]
加了     export JAVA_OPTS="-javaagent:/path/to/atlassian-agent.jar ${JAVA_OPTS}" 这个之后启动报了下面的错

___ Starting the JIRA Plugin System _________________
    
============================== agent working ==============================
============================== agent working ==============================
2019-04-10 00:55:46,222 JIRA-Bootstrap ERROR      [c.a.jira.upgrade.PluginSystemLauncher] A fatal error occured during initialisation. JIRA has been locked.
com.atlassian.jira.InfrastructureException: Error occurred while starting component 'com.atlassian.jira.instrumentation.Instrumentation'.
	at com.atlassian.jira.component.pico.ComponentManager.startStartableComponents(ComponentManager.java:339)
	at com.atlassian.jira.component.pico.ComponentManager.earlyStartPluginSystem(ComponentManager.java:252)
	at com.atlassian.jira.upgrade.PluginSystemLauncher.start(PluginSystemLauncher.java:45)
	at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$postDbLaunch$2(DefaultJiraLauncher.java:145)
	at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.doNowOrEnqueue(DatabaseConfigurationManagerImpl.java:301)
	at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.doNowOrWhenDatabaseActivated(DatabaseConfigurationManagerImpl.java:196)
	at com.atlassian.jira.startup.DefaultJiraLauncher.postDbLaunch(DefaultJiraLauncher.java:137)
	at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$start$0(DefaultJiraLauncher.java:104)
	at com.atlassian.jira.util.devspeed.JiraDevSpeedTimer.run(JiraDevSpeedTimer.java:31)
	at com.atlassian.jira.startup.DefaultJiraLauncher.start(DefaultJiraLauncher.java:102)
	at com.atlassian.jira.startup.LauncherContextListener.initSlowStuff(LauncherContextListener.java:154)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.atlassian.cache.CacheException: java.lang.IllegalStateException: Unable to parse license: AAABdg0ODAoPeNp9UVtPgzAUfudXkPiiD5CyO...
	at com.atlassian.cache.memory.DelegatingCachedReference.get(DelegatingCachedReference.java:92)
	at com.atlassian.jira.license.JiraLicenseManagerImpl.getLicenses(JiraLicenseManagerImpl.java:98)
	at com.atlassian.jira.license.JiraLicenseManagerImpl.getLicenses(JiraLicenseManagerImpl.java:49)
	at com.atlassian.jira.instrumentation.external.InternalStatisticsExternalGauges$1.<init>(InternalStatisticsExternalGauges.java:92)
	at com.atlassian.jira.instrumentation.external.InternalStatisticsExternalGauges.registerLicenceInstruments(InternalStatisticsExternalGauges.java:91)
	at com.atlassian.jira.instrumentation.external.ExternalGauges.installInstruments(ExternalGauges.java:26)
	at com.atlassian.jira.instrumentation.Instrumentation.start(Instrumentation.java:151)
	at com.atlassian.jira.component.pico.ComponentManager.startStartableComponents(ComponentManager.java:335)
	... 11 more
Caused by: java.lang.IllegalStateException: Unable to parse license: AAABdg0ODAoPeNp9UVtPgzAUfudXkPiiD5CyO...
	at com.atlassian.jira.license.LegacyMultiLicenseStore.retrieve(LegacyMultiLicenseStore.java:71)
	at com.atlassian.jira.license.RenaissanceSwitchingMultiLicenseStore.retrieve(RenaissanceSwitchingMultiLicenseStore.java:48)
	at com.atlassian.jira.license.JiraLicenseManagerImpl.loadLicenses(JiraLicenseManagerImpl.java:337)
	at com.atlassian.cache.memory.MemoryCacheManager$1.load(MemoryCacheManager.java:120)
	at com.atlassian.cache.memory.MemoryCacheManager$1.load(MemoryCacheManager.java:96)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.atlassian.cache.memory.DelegatingCachedReference.getUnderLock(DelegatingCachedReference.java:102)
	at com.atlassian.cache.memory.DelegatingCachedReference.get(DelegatingCachedReference.java:87)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Unable to parse license: AAABdg0ODAoPeNp9UVtPgzAUfudXkPiiD5CyO...
	at com.atlassian.jira.license.LegacyMultiLicenseStore$License.<init>(LegacyMultiLicenseStore.java:167)
	at com.atlassian.jira.license.LegacyMultiLicenseStore$License.<init>(LegacyMultiLicenseStore.java:154)
	at com.atlassian.jira.license.LegacyMultiLicenseStore.lambda$retrieve$0(LegacyMultiLicenseStore.java:63)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.atlassian.jira.license.LegacyMultiLicenseStore$Licenses.<init>(LegacyMultiLicenseStore.java:221)
	at com.atlassian.jira.license.LegacyMultiLicenseStore.retrieve(LegacyMultiLicenseStore.java:63)
	... 33 more
Caused by: com.atlassian.extras.common.LicenseException: Failed to verify the license.
	at com.atlassian.extras.decoder.v2.Version2LicenseDecoder.checkAndGetLicenseText(Version2LicenseDecoder.java:187)
	at com.atlassian.extras.decoder.v2.Version2LicenseDecoder.doDecode(Version2LicenseDecoder.java:125)
	at com.atlassian.extras.decoder.api.AbstractLicenseDecoder.decode(AbstractLicenseDecoder.java:15)
	at com.atlassian.extras.decoder.api.DelegatingLicenseDecoder.decode(DelegatingLicenseDecoder.java:44)
	at com.atlassian.extras.core.DefaultLicenseManager.decodeLicense(DefaultLicenseManager.java:77)
	at com.atlassian.extras.core.DefaultLicenseManager.getLicense(DefaultLicenseManager.java:46)
	at com.atlassian.jira.license.LicenseDetailsFactoryImpl$JiraProductLicenseManager.getProductLicense(LicenseDetailsFactoryImpl.java:132)
	at com.atlassian.jira.license.LegacyMultiLicenseStore$License.<init>(LegacyMultiLicenseStore.java:164)
	... 40 more
2019-04-10 00:55:46,290 JIRA-Bootstrap ERROR

**Comment by zfavourite99** [comment]
![image](https://user-images.githubusercontent.com/2630290/55819727-f4c84e00-5b2b-11e9-84a2-850482ae2c71.png)

setenv.sh 里面是这样写的

**Comment by pengzhile** [comment]
你之前是否破解过？是否申请过官方的试用license?

**Comment by zfavourite99** [comment]
有官方试用 license，我再试试从头至尾都用你这个

**Comment by pengzhile** [comment]
jira要先从数据库中移除掉官方的license

**Comment by clhlc** [comment]
同样的问题， 开始用了试用的key，然后用了破解的jar

    ___ Starting the JIRA Plugin System _________________

============================== agent working ==============================
============================== agent working ==============================
^@2019-04-10 03:11:37,811 JIRA-Bootstrap ERROR      [c.a.jira.upgrade.PluginSystemLauncher] A fatal error occured during initialisation. JIRA has been locked.
com.atlassian.jira.InfrastructureException: Error occurred while starting component 'com.atlassian.jira.instrumentation.Instrumentation'.
	at com.atlassian.jira.component.pico.ComponentManager.startStartableComponents(ComponentManager.java:339)
	at com.atlassian.jira.component.pico.ComponentManager.earlyStartPluginSystem(ComponentManager.java:252)
	at com.atlassian.jira.upgrade.PluginSystemLauncher.start(PluginSystemLauncher.java:45)
	at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$postDbLaunch$2(DefaultJiraLauncher.java:145)
	at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.doNowOrEnqueue(DatabaseConfigurationManagerImpl.java:301)
	at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.doNowOrWhenDatabaseActivated(DatabaseConfigurationManagerImpl.java:196)
	at com.atlassian.jira.startup.DefaultJiraLauncher.postDbLaunch(DefaultJiraLauncher.java:137)
	at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$start$0(DefaultJiraLauncher.java:104)
	at com.atlassian.jira.util.devspeed.JiraDevSpeedTimer.run(JiraDevSpeedTimer.java:31)
	at com.atlassian.jira.startup.DefaultJiraLauncher.start(DefaultJiraLauncher.java:102)
	at com.atlassian.jira.startup.LauncherContextListener.initSlowStuff(LauncherContextListener.java:154)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.atlassian.cache.CacheException: com.atlassian.extras.common.LicenseException: Failed to verify the license.
	at com.atlassian.cache.memory.DelegatingCachedReference.get(DelegatingCachedReference.java:92)
	at com.atlassian.jira.license.JiraLicenseManagerImpl.getLicenses(JiraLicenseManagerImpl.java:98)
	at com.atlassian.jira.license.JiraLicenseManagerImpl.getLicenses(JiraLicenseManagerImpl.java:49)
	at com.atlassian.jira.instrumentation.external.InternalStatisticsExternalGauges$1.<init>(InternalStatisticsExternalGauges.java:92)
	at com.atlassian.jira.instrumentation.external.InternalStatisticsExternalGauges.registerLicenceInstruments(InternalStatisticsExternalGauges.java:91)
	at com.atlassian.jira.instrumentation.external.ExternalGauges.installInstruments(ExternalGauges.java:26)
	at com.atlassian.jira.instrumentation.Instrumentation.start(Instrumentation.java:152)
	at com.atlassian.jira.component.pico.ComponentManager.startStartableComponents(ComponentManager.java:335)
	... 11 more
Caused by: com.atlassian.extras.common.LicenseException: Failed to verify the license.
	at com.atlassian.extras.decoder.v2.Version2LicenseDecoder.checkAndGetLicenseText(Version2LicenseDecoder.java:126)
	at com.atlassian.extras.decoder.v2.Version2LicenseDecoder.doDecode(Version2LicenseDecoder.java:72)
	at com.atlassian.extras.decoder.api.AbstractLicenseDecoder.decode(AbstractLicenseDecoder.java:15)
	at com.atlassian.extras.decoder.api.DelegatingLicenseDecoder.decode(DelegatingLicenseDecoder.java:44)
	at com.atlassian.extras.core.DefaultLicenseManager.decodeLicense(DefaultLicenseManager.java:77)
	at com.atlassian.extras.core.DefaultLicenseManager.getLicense(DefaultLicenseManager.java:46)
	at com.atlassian.jira.license.LicenseDetailsFactoryImpl$JiraProductLicenseManager.getProductLicense(LicenseDetailsFactoryImpl.java:132)
	at com.atlassian.jira.license.LicenseDetailsFactoryImpl.getLicense(LicenseDetailsFactoryImpl.java:70)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.atlassian.jira.license.JiraLicenseManagerImpl$CachedLicenses.<init>(JiraLicenseManagerImpl.java:352)
	at com.atlassian.jira.license.JiraLicenseManagerImpl$CachedLicenses.<init>(JiraLicenseManagerImpl.java:340)
	at com.atlassian.jira.license.JiraLicenseManagerImpl.loadLicenses(JiraLicenseManagerImpl.java:337)
	at com.atlassian.cache.memory.MemoryCacheManager$1.load(MemoryCacheManager.java:120)
	at com.atlassian.cache.memory.MemoryCacheManager$1.load(MemoryCacheManager.java:96)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.atlassian.cache.memory.DelegatingCachedReference.getUnderLock(DelegatingCachedReference.java:102)
	at com.atlassian.cache.memory.DelegatingCachedReference.get(DelegatingCachedReference.java:87)

**Comment by zfavourite99** [comment]
我现在已经搞好了，8.1 是可以破解的，从一开始不需要使用试用的 license，直接使用这个jar包生成的 license就可以，选择数据库的时候不要选择内联数据库，会验证失败，直接选择外部数据库（我用的mysql）就可以验证成功。

**Comment by flashing** [comment]
之前数据库有license，可以删除掉：
