### ISSUE TITLE
破解jira时候启动报错

### ISSUE THREAD

**Issue by 94192448** [pengzhile/atlassian-agent#25]
Entity model schema name                      : PUBLIC
         Database Version                              : H2 - 1.4.185 (2015-01-16)
         Database Driver                               : H2 JDBC Driver - 1.4.185 (2015-01-16)
         Database URL                                  : jdbc:h2:file:/var/atlassian/application-data/jira/database/h2db
         Database JDBC config                          : h2 jdbc:h2:file:/var/atlassian/application-data/jira/database/h2db
    
2019-04-15 09:36:20,976 JIRA-Bootstrap INFO      [c.a.jira.startup.JiraStartupLogger] 
    
    ___ Starting the JIRA Plugin System _________________
    
============================== agent working ==============================
============================== agent working ==============================
2019-04-15 09:36:58,424 JIRA-Bootstrap ERROR      [c.a.jira.upgrade.PluginSystemLauncher] A fatal error occured during initialisation. JIRA has been locked.
com.atlassian.jira.InfrastructureException: Error occurred while starting component 'com.atlassian.jira.instrumentation.Instrumentation'.
        at com.atlassian.jira.component.pico.ComponentManager.startStartableComponents(ComponentManager.java:339)
        at com.atlassian.jira.component.pico.ComponentManager.earlyStartPluginSystem(ComponentManager.java:252)
        at com.atlassian.jira.upgrade.PluginSystemLauncher.start(PluginSystemLauncher.java:45)
        at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$postDbLaunch$2(DefaultJiraLauncher.java:145)
        at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.doNowOrEnqueue(DatabaseConfigurationManagerImpl.java:301)
        at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.doNowOrWhenDatabaseActivated(DatabaseConfigurationManagerImpl.java:196)
        at com.atlassian.jira.startup.DefaultJiraLauncher.postDbLaunch(DefaultJiraLauncher.java:137)
        at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$start$0(DefaultJiraLauncher.java:104)
        at com.atlassian.jira.util.devspeed.JiraDevSpeedTimer.run(JiraDevSpeedTimer.java:31)
        at com.atlassian.jira.startup.DefaultJiraLauncher.start(DefaultJiraLauncher.java:102)
        at com.atlassian.jira.startup.LauncherContextListener.initSlowStuff(LauncherContextListener.java:154)

**Comment by pengzhile** [comment]
看起来像是你数据库问题啊

**Comment by szdefine** [comment]
不是数据库问题，我也碰到了，关掉agent就好了。 jira版本8.1
